/* eslint-disable import/no-unresolved */
const pngImages = {
  illustration: require('./dashboard/Illustration_1_small.png'),
  editImage: require('./edit/edit.png'),
  defaultUserImage: require('./drawer/defaultAvatar.jpg'),
  checkIcon: require('./iconsCheck/iconsCheck.png'),
  dividerMenu: require('./Line.png'),
  calenderIcon: require('./briefcase/iconsHeaderCalender.png'),
  backgroundThemeImage: require('./combined_shape.png'),
  editIcon: require('./edit/edit.png'),
  bildsyIcon: require('./bildsy_logo/bildsy_logo.png'),
  bitMapGroup6: require('./bitMap/group6.png'),
  Send: require('./Send.png'),
  download_icon: require('./download_icon.png'),
  view_icon: require('./view_icon.png'),
  link: require('./link.png'),
  backButtonIcon: require('./back_button/iconsBack.png'),
  blogCalender: require('./blogImage/calendar.png'),
  projectIcon: require('./projectIcon/projectIcon.png'),
  newImage: require('./newImage/newImage1.png'),
  editViewProfileIcon: require('./iconEdit/iconEdit.png'),
  iconsInputPhone: require('./iconsInputPhone/iconsInputPhone.png'),
  iconsInputMessage: require('./iconsInputMessage/iconsInputMessage.png'),
  iconsLocation: require('./iconsLocation/iconsLocation.png'),
  pathIcons: require('./path/path.png'),
  defaultCompanyLogo: require('./bitMap/group6.png'),
  crossIcon: require('./Close.png'),
  docIcon: require('./Documents.svg'),
  helpButton: require('./Button.png'),
  addImage: require('./addAttacthment/elementsAddAttachment.png'),
};
export default pngImages;
