import {basePath} from '../../configs';

export const API_END_POINTS = {
  userLogin: 'User/HomeOwnerLogin',
  getCountryList: 'User/GetAllCountry',
  getStateList: 'User/GetAllState?countryId=',
  userSignUp: 'User/HomeOwnerRegister',
  userSignUpAddress: 'User/HomeownerAdvance',
  socialSignIn: 'SocialMediaLogin',
  featuredArticles: 'Dashboard/FeaturedArticles',
  dashboardAds: 'Dashboard/DisplayAds',
  resetPasswordEmailSend: 'User/ForgetPassword',
  verificationCode: 'User/ValidateOTP?email=',
  resetPassword: 'User/ResetPassword',
  getProjectType: 'Project/GetProjectTypes',
  getProjectAreas: 'Project/GetProjectAreas',
  projectProfessionalList: 'Project/ProjectProfessionals?projectId=',
  projectDetails: 'Project/ProjectDetail?id=',
  getSearchProfessionalList: 'Project/SearchFilterProfessional',
  updateProfessional: 'Project/UpdateProjectProfessional',
  createProject: 'Project/CreateProject',
  uploadFile: 'Common/SaveDocument',
  updateProjectDetails: 'Project/UpdateProjectDetail',
  updateLocation: 'Project/UpdateProjectLocation',
  updateSpecifications: 'Project/UpdateProjectSpecification',
  deleteDocument: 'Common/DeleteDocument',
  saveProject: 'Project/SaveProject',
  projectList: 'Project/ProjectList',
  topFiveProjects: 'Dashboard/ProjectActivity',
  signOut: 'User/Logout',
  searchFilterProjectList: 'Project/SearchFilterProjectList',
  locationList: 'Project/LocationList',
  projectTypeDetails: 'Project/ProjectTypeDetail',
  createComplaintPopup: 'Complaints/CreateComplaintPopup',
  getBlogCategory: 'Blog/GetBlogCategory',
  blogPostList: 'Blog/BlogPostList',
  blogDetail: 'Blog/BlogDetail',
  searchBlogPost: 'Blog/SearchBlogPost',
  createComplaint: 'Complaints/SaveComplaint',
  allComplaints: 'Complaints/GetAllComplaints',
  bidsList: 'Bids/BidsList',
  complaintDetails: 'Complaints/ComplaintDetail',
  complaintConversation: 'Complaints/CreateComplaintCustomerConversation',
  complaintChat: 'Complaints/ChatDetail',
  resolveComplaint: 'Complaints/ResolveComplaint',
  userProfileDetail: 'User/HomeOwnerViewProfile',
  userProfileUpdateDetail: 'User/HomeOwnerEditProfile',
  bidsDetail: 'Bids/BidsDetail',
  BidsProfessionalDetail: 'Bids/BidsProfessionalDetail',
  markProjectComplete: 'Project/MarkCompleteProject',
  UpdateBidStatus: 'Bids/UpdateBidStatus',
  getAdsProfessional: 'Dashboard/AdsProfessionalDetail',
  getProfessionalDetail: 'Dashboard/GetProfessionalDetail',
  notificationList: 'Common/NotificationList',
  MarkArchiveProject: 'Project/MarkArchiveProject',
  changePassword: 'User/ChangePassword',
  GetProjectUsers: 'Project/GetProjectUsers',
  GetConfigurationKey: 'Common/GetConfigurationKey',
  adsLead: 'Dashboard/AdsLead',
  UpdateMessageStatusAPI: 'ProfessionalChat/UpdateMessageStatus?projectId=',
  removeAccount: 'User/DeleteCustomer',
  addProReview: 'ProfessionalReview/CreateProfessionalReview',
  getProReview: 'ProfessionalReview/GetReviewByProjectId?projectId=',
  addReviewComment: 'ProfessionalReview/AddConversationComment',
  reportConversation: 'ProfessionalReview/ReviewConversation',
  signUpUserDetails: 'ProfessionalProject/UserDetails',
  emailCheck: 'ProfessionalProject/IsEmailExist',
  proLogin: 'User/ProfessionalLogin',
};
export const URLS = {
  termAndConditions: `${basePath}conditions-of-use?source=mobile`,
  freshDeskURL: 'https://newaccount1625865837700.freshdesk.com/api/v2/tickets',
};
export const SENTRY_DSN = 'https://33f08d427718452d813ba7b33659b973@o1085822.ingest.sentry.io/6097216';
