export const strings = {
  welcome: 'Welcome',
  welcomeBack: 'Welcome Back!',
  signInNow: 'Sign in now',
  emailAddress: 'Email Address',
  password: 'Password',
  noAccount: 'Don’t have an account? ',
  signUp: 'Sign Up',
  forgetPassword: 'Forgot Password?',
  signIn: 'Sign In',
  firstName: 'First Name *',
  lastName: 'Last Name *',
  reEnterPassword: 'Re-enter Password *',
  phone: 'Phone',
  address: 'Address *',
  country: 'Country *',
  state: 'State *',
  city: 'City *',
  zipCode: 'Zip Code *',
  emailAddress2: 'Email Address *',
  password2: 'Password *',
  iAgreeTo: 'I Agree to',
  termsAndConditions: 'Terms and Conditions',
  alreadyHaveAnAccount: 'Already have an account?',
  noInternet: 'No internet connection.',
  pleaseCheckInternetSettings: 'Please check your internet settings.',
  emailPhoneRequired: 'Email / Phone is required',
  passwordRequired: 'Password is required',
  enterValidEmail: 'Enter valid email',
  enterValidPhone: 'Enter valid phone number',
  createProject: 'Create project',
  recentArticles: 'Recent Articles',
  viewAll: 'View All',
  recover: 'Recover',
  verifyAndProceed: 'Verify and Proceed',
  resetPassword: 'Reset Password',
  hireMe: 'Hire Me',
  contactMe: 'Contact Me',
  visitUs: 'Visit Us',
  projectType: 'Project Type *',
  areaSqFit: 'Area (Sq.Feet) *',
  next: 'Next',
  skip: 'Skip',
  previous: 'Previous',
  cancel: 'Cancel',
  confirm: 'Confirm',
  projectDetails: 'Project Details',
  addProject: 'Add Project',
  professionals: 'Professionals',
  details: 'Details',
  projectName: 'Project Name *',
  enterYourProjectName: 'Enter Your Project Name',
  expectedStartDate: 'Expected Start Date *',
  mmddyy: 'YYYY-MM-DD',
  desiredCompletionDate: 'Desired Completion Date *',
  description: 'Description',
  descriptionWithStar: 'Description *',
  typeHere: 'Type Here...',
  location: 'Location',
  pleaseEnterYourAddress: 'Please Enter Your Address',
  selectCountry: 'Select Country',
  stateProvinceRegion: 'State / Province / Region * ',
  selectState: 'Select State',
  phoneNumber: 'Phone Number *',
  code: '+1(301)',
  specification: 'Specification',
  select: 'Select',
  area: 'Area (Sq.Feet)',
  budget: 'Budget (Material + Labor)*',
  usd: 'USD',
  addAttachment: 'Project Attachments',
  addProjectPlan: 'You can add project site plan, maps, site images, etc.',
  inviteProfessionals: 'Invite Professionals',
  selectProfessionals: 'Invites will be sent to Pros listed below',
  inviteBids: 'Invite Bids',
  assignProjectDirectly: 'Assign Project Directly',
  professionalList: 'Professional List',
  contact: 'Contact',
  completionDate: 'Completion Date',
  startDate: 'Start Date',
  projectLocation: 'Project Location',
  addressText: 'Address',
  type: 'Type',
  areaSgFt: 'Area (sq.ft.)',
  budgetText: 'Budget (Material + Labor)',
  professional: 'Professional-',
  attachments: 'Project Attachments',
  pleaseAssignTheProject: 'Please assign the project to one of the Professionals.',
  search: 'Search',
  save: 'Save',
  apply: 'Apply',
  suiteAddress: 'Suite',
  editProject: 'Edit Project',
  editProjectAttachment: 'Edit Project Attachment',
  fromDate: 'From Date',
  toDate: 'To Date',
  companyName: 'Company Name',
  memberSince: 'Member Since',
  localAddress: 'Address',
  aboutMe: 'About Me',
  blogDetails: 'Details',
  viewProfile: 'View Profile',
  editProfile: 'Edit Profile',
  changePassword: 'Change Password',
  setPassword: 'Set your password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  Attachment: 'Attachments',
  RejectBid: 'Reject Bid',
  AwardProject: 'Award Project',
  info_string: 'Once project has been awarded, you can retract project award within 5 minutes.',
  bidPending: 'Bid Pending',
  UnawardProject: 'Unaward Project',
  takeAction: 'Take Action',
  newPassword2: 'New Password*',
  confirmNewPassword2: 'Confirm New Password*',
  error: 'error',
  success: 'success',
  information: 'information',
  error2: 'Error',
  success2: 'Success',
  information2: 'Information',
  info: 'info',
  downloaded: 'Downloaded',
  setPasswordButton: 'Set Password',
  date: 'date',
  yearDateFormate: 'MM/DD/YYYY',
  budgetInfoText: 'Budget may change depending on scope of work',
  rejected: 'Rejected',
  checkEmailInSocialLogin:
    'You have no enabled sharing your email with third party applications, please use regular sign up',
  userEmail: 'userEmail',
  loginButton: 'loginButton',
  googleBtn: 'googleBtn',
  facebookBtn: 'facebookBtn',
  appleBtn: 'appleBtn',
  signUpBtn: 'signUpBtn',
  userFirstName: 'userFirstName',
  userLastName: 'userLastName',
  userAddress: 'userAddress',
  userSuiteAddress: 'userSuiteAddress',
  userCity: 'userCity',
  userZipCode: 'userZipCode',
  userPhone: 'userPhone',
  userNewPassword: 'userNewPassword',
  userNewConfirmPassword: 'userNewConfirmPassword',
  recoverButton: 'recoverButton',
  keyboardDismissButton: 'keyboardDismissButton',
  userVerificationCode: 'userVerificationCode',
  verifyButton: 'verifyButton',
  keyboardDismissBtn: 'keyboardDismissBtn',
  backIconBtn: 'backIconBtn',
  forgotPasswordBtn: 'forgotPasswordBtn',
  userOtp: 'userOtp',
  resendBtn: 'resendBtn',
  nameLimit: 30,
  showResolvedBtn: 'showResolvedBtn',
  downloadFileBtn: 'downloadFileBtn',
  removeDocBtn: 'removeDocBtn',
  showActionSheetButton: 'showActionSheetButton',
  hideComplaintBtn: 'hideComplaintBtn',
  changePasswordBtn: 'changePasswordBtn',
  signOutBtn: 'signOutBtn',
  editProfileBtn: 'editProfileBtn',
  makeCallButton: 'makeCallButton',
  getProfessionalDataBtn: 'getProfessionalDataBtn',
  refreshBtn: 'refreshBtn',
  skipBtn: 'skipBtn',
  submitBtn: 'submitBtn',
  saveProjectDetail: 'saveProjectDetail',
  saveProjectDetail2: 'saveProjectDetail2',
  radioBtn: 'radioBtn',
  readMoreBtn: 'readMoreBtn',
  downloadBtn: 'downloadBtn',
  addIconBtn: 'addIconBtn',
  addNewComplaintBtn: 'addNewComplaintBtn',
  complaintCardBtn: 'complaintCardBtn',
  toggleResponseButton: 'toggleResponseButton',
  nextBtn: 'nextBtn',
  complaintReasonsDropDown: 'complaintReasonsDropDown',
  cancelButton: 'cancelButton',
  toggleButton: 'toggleButton',
  submitButton: 'submitButton',
  hideComplaintButton: 'hideComplaintButton',
  removeDocButton: 'removeDocButton',
  addNewComplaintButton: 'addNewComplaintButton',
  complaintCardButton: 'complaintCardButton',
  messageInputBox: 'messageInputBox',
  removeDocumentButton: 'removeDocumentButton',
  downloadConversationDocumentButton: 'downloadConversationDocumentButton',
  sendMessageButton: 'sendMessageButton',
  removeSelectedImageButton: 'removeSelectedImageButton',
  chatToggleButton: 'chatToggleButton',
  downloadFileDataButton: 'downloadFileDataButton',
  fileDataToggleButton: 'fileDataToggleButton',
  removeFileDataImageButton: 'removeFileDataImageButton',
  backButton: 'backButton',
  showResolvedButton: 'showResolvedButton',
  setProjectDetailVisible: 'setProjectDetailVisible',
  setDescriptionVisible: 'setDescriptionVisible',
  changeLocationButton: 'changeLocationButton',
  setSpecificationVisible: 'setSpecificationVisible',
  changePageButton: 'changePageButton',
  downloadButton: 'downloadButton',
  listDialogButton: 'listDialogButton',
  showToggleButton: 'showToggleButton',
  closeToggleButton: 'closeToggleButton',
  navigationButton: 'navigationButton',
  modalButton: 'modalButton',
  projectAwardButton: 'projectAwardButton',
  toggleDrawerBtn: 'toggleDrawerBtn',
  editProfileImageBtn: 'editProfileImageBtn',
  previousBtn: 'previousBtn',
  addressModelBtn: 'addressModelBtn',
  categoryButton: 'categoryButton',
  toggleMenuButton: 'toggleMenuButton',
  backIconButton: 'backIconButton',
  signOutButton: 'signOutButton',
  updateButton: 'updateButton',
  userOldPassword: 'userOldPassword',
  assignProjectBtn: 'assignBtnWrapper',
  selectProject: 'selectProject',
  toggleBtn: 'toggleBtn',
  mandatoryNewPassword: 'New Password *',
  mandatoryConfirmNewPassword: 'Confirm New Password *',
  fileTripleSlash: 'file:///',
  fileSingleSlash: 'file:/',
  noOfFileError: 'Sorry, total number of files cannot exceed more than 5',
  fileSizeError: 'Your total file size should not exceed 20MB',
  ApiErrorMessage: 'Error: Something went wrong, please try again later !!',
  maxFileUpload: 'Upload files (max 5)',
  ticketRaisedSuccess: 'Ticket Raised Successful',
  supportStaffContact: 'Ticket Created Success! One of our support agent will contact you shortly.',
  toggleMenuBtn: 'toggleMenuBtn',
  contactUs: 'Contact Us',
  fullName: 'Full Name',
  mandatoryEmailAddress: 'Email Address *',
  mandatorySubject: 'Subject *',
  mandatoryDescription: 'Description *',
  submit: 'Submit',
  help: 'Help',
  getProfessionalDataButton: 'getProfessionalDataButton',
  getProfessionalDataButton2: 'getProfessionalDataButton2',
  nextButton: 'nextButton',
  removeButton: 'removeButton',
  toggleDrawerButton: 'toggleDrawerButton',
  editProfileButton: 'editProfileButton',
  editProfileImageButton: 'editProfileImageButton',
  previewsButton: 'previewsButton',
  projectNameWithoutAsterixSign: 'Project Name',
  addressWithoutAsterixSign: 'Address',
  Administrators: 'Administrators',
  name: 'name',
  email: 'email',
  subject: 'subject',
  descriptionEntity: 'description',
  status: 'status',
  priority: 'priority',
  freshDeskUsername: 'L7dhQEs2HO2PYEk7tXpV',
  clearField: 'Clear All',
  signUpButton: 'signUpButton',
  addressModelButton: 'addressModelButton',
  conditionButton: 'conditionButton',
  modelButton: 'modelButton',
  complaintNotFound: 'Complaint not found',
  projectTypeWithoutAsterixSign: 'Project Type',
  skipButton: 'skipButton',
  pageChangeButton: 'pageChangeButton',
  completeButton: 'completeButton',
  archiveToggleButton: 'archiveToggleButton',
  showActionButton: 'showActionButton',
  defaultTimeZone: 'US/Alaska',
  dummyToken: '740f4707bebcf74f9b7c25d48e3358945f6aa01da5ddb387462c7eaf61bb78ad',
  requestQuotes: 'Request Quotes',
  chooseYourPro: 'Choose Your Pro',
  quoteTootTip: 'Request three Pros to quote your project.',
  projectToolTip: 'Choose a Pro that you prefer.',
  addComment: 'Add Comment',
  addNewReviewButton: 'addNewReviewButton',
  addDescription: 'Add Description *',
  rating: 'Rating',
  addPicture: 'Add Picture',
  uptoEight: '(Up to 8)',
  hideReview: 'hideReviewButton',
  reviewButton: 'reviewButton',
  laterButton: 'laterButton',
  addReview: 'Add Review',
  closeIconBtn: 'closeIconBtn',
};
