export const dummyComplaintListResponse = [
  {
    Id: 454,
    ProjectId: 818,
    ProjectName: 'Attachment script ttd ag',
    ComplaintsStatus: 'In Progress',
    ComplaintsStatusId: 10,
    ComplaintsReason: 'Budget Issue',
    Description: 'Without doc',
    CreatedOn: '2022-03-29T19:02:18',
    ResolvedOn: '',
    CustomerId: 28127,
    IsResolveVisible: false,
    RaisedAgainst: null,
    CreatedBy: 1574,
  },
];
export const dummyFileDataProps = [
  {
    EntityId: 668,
    FileName: '1.1_00077290.jpeg',
    FilePath: 'https://bildsydevstorage.blob.core.windows.net/complaintdocuments/1.1_00077290.jpeg',
    Id: 1016,
    fileType: '.jpg',
    fileName: '1.1_00077290.jpeg',
    fileBase64Path: '',
    percent: 100,
    isDownloading: false,
    FileExtension: '',
  },
];

export const adData = [
  {
    Name: 'Ads LeaderBoard 90Ads LeaderBoard 90Ads LeaderBoard 90Ads LeaderBoard',
    Budget: '$1',
    Location: 'San Francisco, CA',
    AdsTypeId: 0,
    StartDate: '2022-02-15T05:30:00',
    EndDate: '2022-02-18T05:30:00',
    Status: 5,
    StepType: 'Confirmation',
    InActiveAds: false,
    IsDeleteAds: false,
    Id: 356,
    AudiencesList: [{City: 'Test', State: 'Test', Value: 'Test'}],
  },
];

export const dummyAdsList = {
  Data: {
    Warning: null,
    NoResults: false,
    q: null,
    sd: null,
    ed: null,
    orderStartDateString: null,
    AvailableLocations: [],
    li: null,
    pti: 0,
    ml: 0,
    PagingFilteringContext: {
      AllowCustomersToSelectPageSize: false,
      PageSizeOptions: [],
      PageIndex: 0,
      PageNumber: 1,
      PageSize: 15,
      TotalItems: 103,
      TotalPages: 7,
      FirstItem: 1,
      LastItem: 15,
      HasPreviousPage: false,
      HasNextPage: true,
      CustomProperties: {},
    },
    AdsOverviews: [
      {
        Name: 'Headline Space Name',
        Budget: '$1',
        Location: 'Cambridge, MA',
        AdsTypeId: 0,
        StartDate: '2021-10-15T05:30:00',
        EndDate: '2021-12-15T05:30:00',
        Status: 5,
        AdStatus: 'InActive',
        AudiencesList: [
          {
            Ads_Id: 309,
            ProjectTypeId: 0,
            Latitude: 42.3705,
            Longitude: -71.072,
            MilesRadius: 1,
            AddressLine: 'Charleston Ave 02141',
            City: 'Cambridge',
            State: 'MA',
            Country: 'United States',
            IsActive: true,
            ProjectType: 0,
            Id: 459,
          },
        ],
        StepType: 'Confirmation',
        InActiveAds: false,
        IsDeleteAds: true,
        Id: 309,
        CustomProperties: {},
      },
    ],
    CustomProperties: {},
  },
  Success: true,
  Message: null,
};

export const dummyComplaintDetails = {
  ProjectId: 818,
  ProjectName: 'Attachment script ttd ag',
  CreatedBy: 1574,
  RaisedAgainst: 'anastasia',
  Budget: '$2,545.00',
  ComplaintsStatus: 'Resolved',
  ComplaintsStatusId: 30,
  ComplaintsReasonsId: 10,
  ComplaintsReason: 'Payment And Budget Issue',
  AvailableReasons: [],
  Description: 'Image uploaded by pro',
  CreatedOn: '2022-03-25T17:13:14',
  ResolvedOn: '2022-03-28T12:38:58',
  ProjectUniqueId: 'PBE30',
  CustomerId: 1574,
  EntityI: 669,
  IsResolveVisible: true,
  Id: 419,
  EntityId: 419,
};

export const complaintsCustomerConversations = [
  {
    Message: 'Send by pro',
    CreatedOn: '2022-03-25T17:56:15',
    CreatedBy: 1574,
    CustomerFullName: 'Test',
    ComplaintDocuments: [
      {
        EntityId: 676,
        FileName: 'images_62548077.jpeg',
        FilePath: 'https://bildsydevstorage.blob.core.windows.net/complaintdocuments/images_62548077.jpeg',
        FileExtension: '.jpeg',
        Id: 1021,
      },
    ],
    Id: 676,
    CustomProperties: {},
  },
];

export const dummyProfessionalListResponse = [
  {
    UsernamesEnabled: false,
    Username: null,
    Email: 'PRO.cat123@yopmail.com',
    Password: null,
    VendorId: 0,
    AvailableVendors: [],
    GenderEnabled: false,
    Gender: null,
    FirstNameEnabled: false,
    FirstName: null,
    LastNameEnabled: false,
    LastName: null,
    FullName: 'PRO Cat DevCheck',
    DateOfBirthEnabled: false,
    DateOfBirth: null,
    CompanyEnabled: false,
    Company: 'nEW cOMPANY NAME pLAN NAME',
    CompanyLogo: 'https://bildsydevstorage.blob.core.windows.net/images/loading-gif_85278843.gif',
    StreetAddressEnabled: false,
    StreetAddress: 'California 99, Los Morions, California, 96055',
    StreetAddress2Enabled: false,
    StreetAddress2: null,
    ZipPostalCodeEnabled: false,
    ZipPostalCode: null,
    CityEnabled: false,
    City: 'Los Morions',
    CountyEnabled: false,
    County: 'United States',
    CountryEnabled: false,
    CountryId: 237,
    AvailableCountries: [
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Select Country',
        Value: '0',
      },
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'United States',
        Value: '237',
      },
    ],
    StateProvinceEnabled: false,
    StateProvinceId: 1678,
    AvailableStates: [
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: 'Select State',
        Value: '0',
      },
    ],
    PhoneEnabled: false,
    Phone: null,
    FaxEnabled: false,
    Fax: null,
    LicenseNumber: null,
    AboutMe: null,
    LocalAddressId: 0,
    CustomerAttributes: [],
    RegisteredInStore: null,
    AdminComment: null,
    IsTaxExempt: false,
    Active: false,
    AffiliateId: 0,
    AffiliateName: null,
    TimeZoneId: null,
    AllowCustomersToSetTimeZone: false,
    AvailableTimeZones: [],
    VatNumber: null,
    VatNumberStatusNote: null,
    DisplayVatNumber: false,
    DisplayRegisteredInStore: false,
    StateName: 'California',
    CountryName: null,
    TwoLetterIsoCode: 'US',
    CreatedOn: '2022-02-17T14:10:56',
    LastActivityDate: '2022-04-25T21:09:01',
    LastIpAddress: null,
    LastVisitedPage: null,
    CustomerRoleNames: 'Registered, Professional',
    AvailableCustomerRoles: [],
    SelectedCustomerRoleIds: [],
    AvailableNewsletterSubscriptionStores: [],
    SelectedNewsletterSubscriptionStoreIds: [],
    ProjectTypeId: 4,
    DisplayRewardPointsHistory: false,
    AddRewardPoints: {
      CustomerId: 0,
      Points: 0,
      Message: null,
      StoreId: 0,
      AvailableStores: [],
      ActivatePointsImmediately: false,
      ActivationDelay: 0,
      ActivationDelayPeriodId: 0,
      PointsValidity: null,
      CustomProperties: {},
    },
    CustomerRewardPointsSearchModel: {
      CustomerId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    AllowSendingOfPrivateMessage: false,
    AllowSendingOfWelcomeMessage: false,
    AllowReSendingOfActivationMessage: false,
    GdprEnabled: false,
    AvatarUrl: 'https://bildsydevstorage.blob.core.windows.net/images/default-avatar_120.jpg',
    CustomerAddressSearchModel: {
      CustomerId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    CustomerOrderSearchModel: {
      CustomerId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    CustomerShoppingCartSearchModel: null,
    CustomerActivityLogSearchModel: null,
    CustomerBackInStockSubscriptionSearchModel: null,
    CustomerAssociatedExternalAuthRecordsSearchModel: null,
    WorkRadius: 0,
    WorkRadiusUnit: 'Miles',
    IsBildsyAssured: false,
    Id: 23830,
  },
];
export const infoDocumentData = [
  {
    percent: 1,
    isDownloading: true,
    ProjectId: 869,
    FileName: '7F8ACBCC-B145-4D4B-B297-3B5070FF00D1.jpg',
    FileExtension: '.jpg',
    FilePath:
      'https://bildsydevstorage.blob.core.windows.net/projectdocuments/7F8ACBCC-B145-4D4B-B297-3B5070FF00D1_53109530.jpg',
    Id: 1031,
  },
];

export const dummyProjectInfo = {
  Data: {
    Name: 'Estimator Details after Project Awarded',
    ProjectStatus: null,
    ProjectStatusId: 0,
    BidStatus: 'Bid Pending',
    BidStatusId: 40,
    ExpectedStartDateUTC: '2022-04-13T05:30:00',
    ExpectedCompleteDateUTC: '2022-04-26T05:30:00',
    Description:
      'Estimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project AwardedEstimator Details after Project Awarded',
    CustomerId: 1588,
    CustomerName: 'Anastasia test test test',
    Address: {
      FirstName: 'Anastasia',
      LastName: '',
      Email: 'jackson@galaxyinfotech.co',
      CompanyEnabled: false,
      CompanyRequired: false,
      Company: null,
      CountryEnabled: true,
      CountryId: 237,
      CountryName: 'United States',
      StateProvinceEnabled: true,
      StateProvinceId: 1699,
      StateProvinceName: 'Michigan',
      CountyEnabled: false,
      CountyRequired: false,
      County: null,
      CityEnabled: true,
      CityRequired: true,
      City: 'Insphering',
      StreetAddressEnabled: true,
      StreetAddressRequired: true,
      Address1: 'Road Ppg',
      StreetAddress2Enabled: false,
      StreetAddress2Required: false,
      Address2: null,
      ZipPostalCodeEnabled: true,
      ZipPostalCodeRequired: true,
      ZipPostalCode: '49849',
      PhoneEnabled: true,
      PhoneRequired: false,
      PhoneNumber: '(423) 535-3535',
      FaxEnabled: false,
      FaxRequired: false,
      FaxNumber: null,
      AvailableCountries: [],
      AvailableStates: [],
      FormattedCustomAddressAttributes: '',
      CustomAddressAttributes: [],
      GoogleApiKey: null,
      Longitude: -87.723881,
      Latitude: 46.455012,
      Suite: null,
      Id: 3013,
      CustomProperties: {},
    },
    ProjectTypeId: 4,
    ProjectType: 'Exterior Project',
    AreaSqFeet: '2000+',
    Budget: '$333.00',
    BudgetAmount: 333,
    Attachments: infoDocumentData,
    ProjectAwardedDateTimeUTC: null,
    ProjectUniqueId: 'TPB6V',
    IsArchived: false,
    IsArchivedByProfessional: false,
    Id: 861,
    CustomProperties: {},
  },
  Success: true,
  Message: null,
};

export const dummyUserDetail = {
  Data: {
    FirstName: 'Chettan',
    LastName: 'Saxena',
    AvatarUrl: 'https://bildsydevstorage.blob.core.windows.net/images/0001137_Cap_GIF%20%281%29_48118157.gif',
    FullName: 'Chettan Saxena',
    CustomerRoleName: 'HomeOwner',
    Email: 'prakhar.saxena@galaxyweblinks.in',
    Phone: '(012) 345-6789',
    MemberSince: '2021-08-10T07:46:23',
    StreetAddress: ' Charlestown Avenue, NH155, Cambridge, Washington, 02141',
    Address1: 'Charlestown Avenue',
    Suite: 'NH155',
    StateProvinceId: 1728,
    StateProvinceName: 'Washington',
    City: 'Cambridge',
    Longitude: -71.072011,
    Latitude: 42.37055,
    ZipPostalCode: '02141',
  },
  Success: true,
  Message: null,
};
export const bidsListResponseDummyData = {
  Data: {
    AvailableBid: [
      {
        CustomerName: '',
        CustomerType: 'Exterior Project, Interior Project, New Construction, Other, Renovation',
        BidPrice: '$0.00',
        ProposalDescripton: null,
        ProposalDescription: null,
        ProjectId: 0,
        AwardedProject: true,
        BidTimeInDays: '27 Days ago',
        BidId: 554,
        StatusValue: 'Bid Declined',
        Status: 50,
        IsBildsyAssured: false,
        CustomerId: 27757,
        Phone: '(789) 654-1239',
        CompanyName: 'Fast company',
        CompanyLogo: 'http://20.225.146.22/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
        ProjectStartOnUTC: '2022-04-28T07:11:27',
        ProjectDeliveredOnUTC: '2022-04-28T07:11:27',
        Attachments: [],
      },
      {
        CustomerName: 'PRO Cat DevCheck',
        CustomerType: 'Exterior Project, Interior Project, New Construction, Other, Renovation',
        BidPrice: '$1,222.00',
        ProposalDescripton:
          'Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsd',
        ProposalDescription:
          'Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsd',
        ProjectId: 0,
        AwardedProject: true,
        BidTimeInDays: '27 Days ago',
        BidId: 555,
        StatusValue: 'Project Awarded',
        Status: 30,
        IsBildsyAssured: false,
        CustomerId: 23830,
        Phone: '(433) 434-4454',
        CompanyName: 'nEW cOMPANY NAME pLAN NAME',
        CompanyLogo: '',
        ProjectStartOnUTC: '2022-04-29T00:00:00',
        ProjectDeliveredOnUTC: '2022-05-25T00:00:00',
        Attachments: [],
      },
    ],
    ProjectId: 874,
    Attachments: [],
    InvitedProfessionals: [
      {
        ProfessionalId: 29320,
        ProfessionalName: 'john Stripe android',
        ProfessionalEmail: 'johny.stripe@yopmail.com',
        ProfessionalType: 'Exterior Project, Interior Project, New Construction',
        IsLoggedInUser: false,
        InvitedDate: '2022-04-28T07:01:34',
        IsBildsyAssured: false,
        CompanyName: 'Test',
        CompanyLogo: 'http://20.225.146.22/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
        Phone: '(454) 555-5555',
        AvatarUrl: 'https://bildsydevstorage.blob.core.windows.net/images/default-avatar_120.jpg',
        QuickBloxUserId: '134287792',
        NoAvailableBidStatus: 'Bid Lost',
        Id: 0,
        CustomProperties: {},
      },
    ],
  },
};
export const blogCategoryResponseDummyData = {
  Data: [
    {
      Name: 'DIY',
      DisplayOrder: 3,
      Published: true,
      SeName: null,
      MetaTitle: null,
      MetaKeywords: null,
      MetaDescription: null,
      Id: 31,
    },
  ],
  Success: true,
  Message: null,
};

export const blogCategoryDummyData = [
  {
    Name: 'DIY',
    DisplayOrder: 3,
    Published: true,
    SeName: null,
    MetaTitle: null,
    MetaKeywords: null,
    MetaDescription: null,
    Id: 31,
  },
];

export const blogListResponseDummyData = {
  Data: {
    WorkingLanguageId: 1,
    PagingFilteringContext: {
      Month: null,
      Tag: null,
      AllowCustomersToSelectPageSize: false,
      PageSizeOptions: [],
      Q: null,
      Status: null,
      Sid: 0,
      PageIndex: 0,
      PageNumber: 1,
      PageSize: 15,
      TotalItems: 1,
      TotalPages: 1,
      FirstItem: 1,
      LastItem: 1,
      HasPreviousPage: false,
      HasNextPage: false,
      CustomProperties: {},
    },
    BlogPosts: [
      {
        MetaKeywords: null,
        MetaDescription: null,
        MetaTitle: null,
        SeName: '8-april-2022-admin-blog',
        RedirectTo: null,
        Title: '8 April 2022 Admin Blog',
        Body: '<p>8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog</p>',
        BodyOverview:
          '8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog',
        AllowComments: false,
        NumberOfComments: 0,
        CreatedOn: '2022-04-08T19:00:09',
        Tags: [],
        Comments: [],
        AddNewComment: {
          CommentText: null,
          DisplayCaptcha: false,
          Id: 0,
          CustomProperties: {},
        },
        DefaultPictureModel: {
          ImageUrl: 'http://20.225.146.22/images/default-image-blog.png',
          ThumbImageUrl: null,
          FullSizeImageUrl: 'http://20.225.146.22/images/default-image-blog.png',
          Title: 'Show details for 8 April 2022 Admin Blog',
          AlternateText: 'Picture of 8 April 2022 Admin Blog',
          CustomProperties: {},
        },
        CreatedBy: 1,
        CreatedByName: 'Bildsy Admin',
        BlogCategoryId: 31,
        BlogCategoryName: 'DIY',
        BlogPostStatusId: 10,
        BlogPostStatus: 'Approved',
        RejectReason: '',
        CustomerAvatar: '',
        CreatedByValue: null,
        CompanyName: null,
        Id: 167,
        CustomProperties: {},
      },
    ],
    CustomProperties: {},
  },
  Success: true,
  Message: null,
};

export const fileDummyData = {
  name: 'Test Image',
  size: 1,
  id: '123456',
  type: '.jpg',
  contentType: '.jpg',
  uid: '1060',
  FilePath: 'https://bildsydevstorage.blob.core.windows.net/complaintdocuments/1.1_00077290.jpeg',
  FileName: '1.1_00077290.jpeg',
  fileName: '1.1_00077290.jpeg',
  fileType: '.jpg',
  FileExtension: '.jpg',
  uri: 'https://bildsydevstorage.blob.core.windows.net/complaintdocuments/1.1_00077290.jpeg',
};

export const bidDetailResponseDummyData = {
  Data: {
    BidAttachments: [fileDummyData],
    BidId: 555,
    BidPlacedOn: '27 Days ago',
    BidPlacedOnTime: '2022-04-28T07:12:35',
    BidPrice: '$1,222.00',
    BidStatus: null,
    CompanyLogo: '',
    CompanyName: 'nEW cOMPANY NAME pLAN NAME',
    CustomerSince: '2022-02-17T08:40:56',
    Phone: '(433) 434-4454',
    ProfessionalId: 23830,
    ProfessionalName: 'PRO Cat DevCheck',
    ProjectAwarded: true,
    ProjectDeliveredOnUTC: '2022-05-25T00:00:00',
    ProjectId: 874,
    ProjectIsDeleted: false,
    ProjectStartOnUTC: '2022-04-29T00:00:00',
    ProjectTitle: 'Test Bid Lost when Reject',
    ProposalDescription:
      'Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid PendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsdCondition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pending Condition HO create the Project and invite the 1 or more than 1 Professionals as Status Bid Pendingfdfdsfsdfsfsfsfsfsfsfsfsfsdfsd',
    Status: 30,
    TimeOut: true,
  },
  Message: null,
  Success: true,
};

export const BidsProfessionalDetailDummyData = {
  Data: {
    ProfessionalId: 23830,
    ProfessionalName: 'PRO Cat DevCheck',
    AvatarUrl: 'https://bildsydevstorage.blob.core.windows.net/images/default-avatar_120.jpg',
    BidId: 542,
    CompanyLogo: '',
    CompanyName: 'nEW cOMPANY NAME pLAN NAME',
    AboutMe: null,
    CustomerSince: '2022-02-17T08:40:56',
    Phone: '(433) 434-4454',
    StreetAddress: 'California 99, Los Morions, California, 96055',
    Address1: 'California 99',
    Suite: null,
    CountryId: 237,
    Country: 'United States',
    StateProvinceId: 1678,
    StateProvinceName: 'California',
    TwoLetterIsoCode: 'US',
    City: 'Los Morions',
    ZipPostalCode: '96055',
  },
  Success: true,
  Message: null,
};
export const blogPostListDummyData = [
  {
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: '8-april-2022-admin-blog',
    RedirectTo: null,
    Title: '8 April 2022 Admin Blog',
    Body: '<p>8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog</p>',
    BodyOverview:
      '8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog8 April 2022 Admin Blog',
    AllowComments: false,
    NumberOfComments: 0,
    CreatedOn: '2022-04-08T19:00:09',
    Tags: [],
    Comments: [],
    AddNewComment: {
      CommentText: null,
      DisplayCaptcha: false,
      Id: 0,
      CustomProperties: {},
    },
    DefaultPictureModel: {
      ImageUrl: 'http://20.225.146.22/images/default-image-blog.png',
      ThumbImageUrl: null,
      FullSizeImageUrl: 'http://20.225.146.22/images/default-image-blog.png',
      Title: 'Show details for 8 April 2022 Admin Blog',
      AlternateText: 'Picture of 8 April 2022 Admin Blog',
      CustomProperties: {},
    },
    CreatedBy: 1,
    CreatedByName: 'Bildsy Admin',
    BlogCategoryId: 31,
    BlogCategoryName: 'DIY',
    BlogPostStatusId: 10,
    BlogPostStatus: 'Approved',
    RejectReason: '',
    CustomerAvatar: '',
    CreatedByValue: null,
    CompanyName: null,
    Id: 167,
    CustomProperties: {},
  },
];

export const dummyLoginResponse = {
  Success: true,
  AccessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicHJha2hhci5zYXhlbmFAZ2FsYXh5d2VibGlua3MuaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiI5MTAzIiwianRpIjoiZjliNjNlMzYtZThjMy00ZDg1LTk4YzctZDM0YTgzNDBlYmRjIiwiZXhwIjoxNjg5OTQzMzA2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyMjE0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MjIxNCJ9.HwxSBYTPjqxeG-Crial0RBDOYhOAAaVdaBagN6Xt3FQ',
  Data: {
    UserType: null,
    Email: 'prakhar.saxena@galaxyweblinks.in',
    EmailToRevalidate: null,
    CheckUsernameAvailabilityEnabled: false,
    AllowUsersToChangeUsernames: false,
    UsernamesEnabled: false,
    Username: 'prakhar.saxena@galaxyweblinks.in',
    GenderEnabled: true,
    Gender: null,
    FirstNameEnabled: true,
    FirstName: 'Chetan13',
    FirstNameRequired: true,
    LastNameEnabled: true,
    LastName: 'Saxena',
    LastNameRequired: true,
    DateOfBirthEnabled: true,
    DateOfBirthDay: null,
    DateOfBirthMonth: null,
    DateOfBirthYear: null,
    DateOfBirthRequired: false,
    StepInformation: 0,
    CompanyLogo: 'https://dev.bildsy.com/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
    CompanyEnabled: false,
    CompanyRequired: false,
    Company: null,
    StreetAddressEnabled: false,
    StreetAddressRequired: false,
    StreetAddress: null,
    StreetAddress2Enabled: false,
    StreetAddress2Required: false,
    StreetAddress2: null,
    ZipPostalCodeEnabled: true,
    ZipPostalCodeRequired: false,
    ZipPostalCode: '02141',
    CityEnabled: false,
    CityRequired: false,
    City: 'Cambridge',
    CountyEnabled: false,
    CountyRequired: false,
    County: null,
    CountryEnabled: true,
    CountryRequired: false,
    CountryId: 237,
    AvailableCountries: [],
    StateProvinceEnabled: true,
    StateProvinceRequired: true,
    StateProvinceId: 1728,
    AvailableStates: [],
    PhoneEnabled: false,
    PhoneRequired: false,
    Phone: '(012) 345-6789',
    FaxEnabled: false,
    FaxRequired: false,
    Fax: null,
    NewsletterEnabled: true,
    Newsletter: false,
    SignatureEnabled: false,
    Signature: null,
    TimeZoneId: null,
    AllowCustomersToSetTimeZone: false,
    AvailableTimeZones: [],
    VatNumber: null,
    VatNumberStatusNote: 'Unknown',
    DisplayVatNumber: false,
    AssociatedExternalAuthRecords: [],
    NumberOfExternalAuthenticationProviders: 2,
    AllowCustomersToRemoveAssociations: true,
    CustomerAttributes: [],
    GdprConsents: [],
    ProjectLicenseList: [],
    QuickBloxLoginName: 'prakharsaxenagalaxyweblinksin9103',
    QuickBloxUserId: '135148218',
    IsDocumentVerify: false,
    IsAddressCapture: true,
    State: null,
    PhoneNumber: null,
    LicenseNumber: null,
    AboutMe: null,
    LocalAddressId: 1450,
    WorkRadius: null,
    WorkRadiusUnit: null,
    AvatarUrl: 'https://bildsydevstg.blob.core.windows.net/images/1474F0A5-1C00-48A7-9D54-90CAC6089F35_36961353.jpg',
    CreatedOnUTC: '2021-08-10T07:46:23',
    LocallAddress: ' Charlestown Avenue',
    CustomerId: 9103,
    FullName: 'Chetan13 Saxena',
    LocalAddress: {
      CountryId: null,
      CountryName: null,
      StateProvinceId: null,
      StateProvinceName: null,
      Abbreviation: null,
      City: null,
      Address1: null,
      ZipPostalCode: null,
      AvailableCountries: [],
      AvailableStates: [],
      GoogleApiKey: null,
      Longitude: 0,
      Latitude: 0,
      Suite: null,
      Id: 0,
      CustomProperties: {},
    },
    SiteAddress1: null,
    SiteAddress2: null,
    Skills: [],
    Addresses: [],
    IsBildsyAssured: false,
    GoogleApiKey: null,
    Longitude: -71.072011,
    Latitude: 42.37055,
    LicenseType: null,
    IsAccountHold: false,
    Suite: null,
    LicenseInfo: [],
    AvailableState: [],
    IsInvitedUser: false,
    HideAddButton: false,
    LoginType: 0,
    CustomProperties: {},
  },
};
export const dummyNotificationData = {
  Data: {
    PagingFilteringContext: {
      PageIndex: 0,
      PageNumber: 1,
      PageSize: 15,
      TotalItems: 14,
      TotalPages: 1,
      FirstItem: 1,
      LastItem: 14,
      HasPreviousPage: false,
      HasNextPage: false,
      CustomProperties: {},
    },
    NotificationLogs: [
      {
        Id: 208,
        NotificationFrom: 1588,
        CustomerId: 1574,
        Title: 'New Conversation for the Complaint',
        Message: "Obrien Abelardo LLC has sent you a new message  regarding complaint 'Unprofessional Behavior'",
        PictureUrl: 'https://dev.bildsy.com/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
        LinkUrl: 'https://dev.bildsy.com/project/info/828',
        TimeAgo: 'April 05, 2022',
        CreatedOnUTC: '2022-04-05T06:55:45',
        IsRead: false,
        EntityId: 467,
        EntityType: 20,
        ProjectId: 828,
        IsProjectActive: true,
      },
    ],
  },
  Success: true,
  Message: null,
};

export const dummyProjectListData = {
  Warning: null,
  NoResults: false,
  q: null,
  sd: null,
  ed: null,
  PagingFilteringContext: {
    AllowCustomersToSelectPageSize: false,
    PageSizeOptions: [],
    PageIndex: 0,
    PageNumber: 1,
    PageSize: 15,
    TotalItems: 74,
    TotalPages: 5,
    FirstItem: 1,
    LastItem: 15,
    HasPreviousPage: false,
    HasNextPage: true,
    CustomProperties: {},
  },
  ProjectOverviews: [
    {
      Name: 'Test Bld 1875',
      ProjectStatus: 'Bidding',
      ProjectStatusId: 60,
      ExpectedStartDateUTC: '2022-07-07T05:30:00',
      ExpectedCompleteDateUTC: '2022-07-07T05:30:00',
      Description:
        'Google Translate  Download languages to use offline  Translate text images handwriting or speechGoogle Translate  Download languages to use offline  Translate text images handwriting or speech Google Translate  Download languages to use offline  Translate text images handwriting or speech',
      CustomerId: 9103,
      CustomerName: 'Chetan13 Saxena',
      Address: {
        FirstName: 'test',
        LastName: 'user',
        Email: 'testu0989@gmail.com',
        CompanyEnabled: false,
        CompanyRequired: false,
        Company: 'Bildsy',
        CountryEnabled: true,
        CountryId: 237,
        CountryName: 'United States',
        StateProvinceEnabled: true,
        StateProvinceId: 1678,
        StateProvinceName: 'California',
        CountyEnabled: false,
        CountyRequired: false,
        County: null,
        CityEnabled: true,
        CityRequired: true,
        City: 'Los Molinos',
        StreetAddressEnabled: true,
        StreetAddressRequired: true,
        Address1: 'California 99',
        StreetAddress2Enabled: false,
        StreetAddress2Required: false,
        Address2: null,
        ZipPostalCodeEnabled: true,
        ZipPostalCodeRequired: true,
        ZipPostalCode: '96055',
        PhoneEnabled: true,
        PhoneRequired: false,
        PhoneNumber: '',
        FaxEnabled: false,
        FaxRequired: false,
        FaxNumber: null,
        AvailableCountries: [],
        AvailableStates: [],
        FormattedCustomAddressAttributes: '',
        CustomAddressAttributes: [],
        GoogleApiKey: null,
        Longitude: 0,
        Latitude: 0,
        Suite: null,
        Id: 3869,
        CustomProperties: {},
      },
      ProjectTypeId: 4,
      ProjectType: 'Exterior Project',
      AreaSqFeet: '100-500',
      Budget: '$8,000.00',
      BudgetAmount: 8000,
      BidStatus: 'Bid Rejected',
      IsEditable: true,
      IsArchived: false,
      IsActiveArchived: false,
      IsComplaintVisible: false,
      IsArchivedByProfessional: false,
      Attachments: [
        {
          ProjectId: 1075,
          FileName: 'rn_image_picker_lib_temp_560fdfe5-3ee7-4b06-8124-e1549a89ac4f.jpg',
          FileExtension: '.jpg',
          FilePath:
            'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_560fdfe5-3ee7-4b06-8124-e1549a89ac4f_01512584.jpg',
          Id: 1090,
          CustomProperties: {},
        },
        {
          ProjectId: 1075,
          FileName: 'rn_image_picker_lib_temp_25304cb9-2853-4ee5-a5a5-9a81cc6ae54d.gif',
          FileExtension: '.gif',
          FilePath:
            'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_25304cb9-2853-4ee5-a5a5-9a81cc6ae54d_35489979.gif',
          Id: 1091,
          CustomProperties: {},
        },
        {
          ProjectId: 1075,
          FileName: 'rn_image_picker_lib_temp_cd85d39f-0efb-4c42-a0f4-3be8edbd6881.jpg',
          FileExtension: '.jpg',
          FilePath:
            'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_cd85d39f-0efb-4c42-a0f4-3be8edbd6881_64730001.jpg',
          Id: 1092,
          CustomProperties: {},
        },
      ],
      BidAttachments: [
        {
          EntityId: 1299,
          FileName: 'A779E795-EDAD-440A-9FCA-D6822C1833D2_38478901.jpg',
          FileExtension: '.jpg',
          FilePath:
            'https://bildsydevstg.blob.core.windows.net/biddocuments/A779E795-EDAD-440A-9FCA-D6822C1833D2_38478901.jpg',
        },
      ],
      Bids: {
        BidGuid: '7459f55d-1f95-4082-9cb8-799e745a6051',
        InvitationId: 2873,
        ProjectId: 1075,
        CustomerId: 23830,
        BidAmount: 1000,
        CurrencyId: 1,
        ProposalDescription:
          'preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop',
        ProjectStartOnUTC: '2022-07-11T00:00:00',
        ProjectDeliveredOnUTC: '2022-11-11T00:00:00',
        BidStatusId: 20,
        CreatedOnUTC: '2022-07-11T11:44:30',
        UpdatedOnUTC: '2022-07-11T11:44:30',
        QueuedEmailId: 0,
        IsPushSend: null,
        BidStatus: 20,
        Id: 729,
      },
      ProjectInvitations: [],
      InvitedProfessionals: [
        {
          ProfessionalId: 23830,
          ProfessionalName: 'PRO Cat DevChec..',
          ProfessionalEmail: 'PRO.cat123@yopmail.com',
          ProfessionalType: 'Exterior Project, Interior Project, New Construction, Other, Renovation',
          IsLoggedInUser: true,
          InvitedDate: '2022-07-08T07:28:45',
          IsBildsyAssured: false,
          CompanyName: 'nEW cOMPANY NAME pLAN NAME',
          CompanyLogo: 'https://dev.bildsy.com/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
          Phone: '(433) 434-4454',
          AvatarUrl: 'https://bildsydevstg.blob.core.windows.net/images/default-avatar_55.jpg',
          QuickBloxUserId: '135212613',
          NoAvailableBidStatus: null,
          Id: 0,
          CustomProperties: {},
        },
      ],
      ProjectAwardedDateTimeUTC: null,
      Complaints: [],
      ProjectUniqueId: 'X5NZD',
      IsBidPlaced: false,
      BidCount: 0,
      CreatedOnDateUTC: '2022-07-07T20:01:47',
      AreaSqFeetId: 2,
      ProjectId: 0,
      IsProfessionalBidStatus: false,
      ShareEstimateToHo: false,
      ProjectBidStatus: 20,
      ProjectActualStatus: 60,
      ProfessionalPhone: null,
      ProfessionalBidPlaced: false,
      IsImpersonate: false,
      ProjectIsDeleted: false,
      Id: 1075,
      CustomProperties: {},
    },
  ],
  ProjectBidOverviews: null,
  CustomProperties: {},
};

export const projectListData = {
  Name: 'Test Bld 1875',
  ProjectStatus: 'Bidding',
  ProjectStatusId: 20,
  ExpectedStartDateUTC: '2022-07-07T05:30:00',
  ExpectedCompleteDateUTC: '2022-07-07T05:30:00',
  Description:
    'Google Translate  Download languages to use offline  Translate text images handwriting or speechGoogle Translate  Download languages to use offline  Translate text images handwriting or speech Google Translate  Download languages to use offline  Translate text images handwriting or speech',
  CustomerId: 9103,
  CustomerName: 'Chetan13 Saxena',
  Address: {
    FirstName: 'test',
    LastName: 'user',
    Email: 'testu0989@gmail.com',
    CompanyEnabled: false,
    CompanyRequired: false,
    Company: 'Bildsy',
    CountryEnabled: true,
    CountryId: 237,
    CountryName: 'United States',
    StateProvinceEnabled: true,
    StateProvinceId: 1678,
    StateProvinceName: 'California',
    CountyEnabled: false,
    CountyRequired: false,
    County: null,
    CityEnabled: true,
    CityRequired: true,
    City: 'Los Molinos',
    StreetAddressEnabled: true,
    StreetAddressRequired: true,
    Address1: 'California 99',
    StreetAddress2Enabled: false,
    StreetAddress2Required: false,
    Address2: null,
    ZipPostalCodeEnabled: true,
    ZipPostalCodeRequired: true,
    ZipPostalCode: '96055',
    PhoneEnabled: true,
    PhoneRequired: false,
    PhoneNumber: '',
    FaxEnabled: false,
    FaxRequired: false,
    FaxNumber: null,
    AvailableCountries: [],
    AvailableStates: [],
    FormattedCustomAddressAttributes: '',
    CustomAddressAttributes: [],
    GoogleApiKey: null,
    Longitude: 0,
    Latitude: 0,
    Suite: null,
    Id: 3869,
    CustomProperties: {},
  },
  ProjectTypeId: 4,
  ProjectType: 'Exterior Project',
  AreaSqFeet: '100-500',
  Budget: '$8,000.00',
  BudgetAmount: 8000,
  BidStatus: 'Bid Rejected',
  IsEditable: true,
  IsArchived: false,
  IsActiveArchived: false,
  IsComplaintVisible: true,
  IsArchivedByProfessional: false,
  Attachments: [
    {
      ProjectId: 1075,
      FileName: 'rn_image_picker_lib_temp_560fdfe5-3ee7-4b06-8124-e1549a89ac4f.jpg',
      FileExtension: '.jpg',
      FilePath:
        'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_560fdfe5-3ee7-4b06-8124-e1549a89ac4f_01512584.jpg',
      Id: 1090,
      CustomProperties: {},
    },
    {
      ProjectId: 1075,
      FileName: 'rn_image_picker_lib_temp_25304cb9-2853-4ee5-a5a5-9a81cc6ae54d.gif',
      FileExtension: '.gif',
      FilePath:
        'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_25304cb9-2853-4ee5-a5a5-9a81cc6ae54d_35489979.gif',
      Id: 1091,
      CustomProperties: {},
    },
    {
      ProjectId: 1075,
      FileName: 'rn_image_picker_lib_temp_cd85d39f-0efb-4c42-a0f4-3be8edbd6881.jpg',
      FileExtension: '.jpg',
      FilePath:
        'https://bildsydevstg.blob.core.windows.net/projectdocuments/rn_image_picker_lib_temp_cd85d39f-0efb-4c42-a0f4-3be8edbd6881_64730001.jpg',
      Id: 1092,
      CustomProperties: {},
    },
  ],
  BidAttachments: [
    {
      EntityId: 1299,
      FileName: 'A779E795-EDAD-440A-9FCA-D6822C1833D2_38478901.jpg',
      FileExtension: '.jpg',
      FilePath:
        'https://bildsydevstg.blob.core.windows.net/biddocuments/A779E795-EDAD-440A-9FCA-D6822C1833D2_38478901.jpg',
    },
  ],
  Bids: {
    BidGuid: '7459f55d-1f95-4082-9cb8-799e745a6051',
    InvitationId: 2873,
    ProjectId: 1075,
    CustomerId: 23830,
    BidAmount: 1000,
    CurrencyId: 1,
    ProposalDescription:
      'preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop preDevelop',
    ProjectStartOnUTC: '2022-07-11T00:00:00',
    ProjectDeliveredOnUTC: '2022-11-11T00:00:00',
    BidStatusId: 20,
    CreatedOnUTC: '2022-07-11T11:44:30',
    UpdatedOnUTC: '2022-07-11T11:44:30',
    QueuedEmailId: 0,
    IsPushSend: null,
    BidStatus: 20,
    Id: 729,
  },
  ProjectInvitations: [],
  InvitedProfessionals: [
    {
      ProfessionalId: 23830,
      ProfessionalName: 'PRO Cat DevChec..',
      ProfessionalEmail: 'PRO.cat123@yopmail.com',
      ProfessionalType: 'Exterior Project, Interior Project, New Construction, Other, Renovation',
      IsLoggedInUser: true,
      InvitedDate: '2022-07-08T07:28:45',
      IsBildsyAssured: false,
      CompanyName: 'nEW cOMPANY NAME pLAN NAME',
      CompanyLogo: 'https://dev.bildsy.com/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
      Phone: '(433) 434-4454',
      AvatarUrl: 'https://bildsydevstg.blob.core.windows.net/images/default-avatar_55.jpg',
      QuickBloxUserId: '135212613',
      NoAvailableBidStatus: null,
      Id: 0,
      CustomProperties: {},
    },
  ],
  ProjectAwardedDateTimeUTC: null,
  Complaints: [],
  ProjectUniqueId: 'X5NZD',
  IsBidPlaced: false,
  BidCount: 0,
  CreatedOnDateUTC: '2022-07-07T20:01:47',
  AreaSqFeetId: 2,
  ProjectId: 0,
  IsProfessionalBidStatus: false,
  ShareEstimateToHo: false,
  ProjectBidStatus: 20,
  ProjectActualStatus: 60,
  ProfessionalPhone: 789878987,
  ProfessionalBidPlaced: false,
  IsImpersonate: false,
  ProjectIsDeleted: false,
  Id: 1075,
  CustomProperties: {},
};

export const professionalData = {
  Data: {
    ProfessionalModel: [
      {
        UsernamesEnabled: false,
        Username: null,
        Email: 'PRO.cat123@yopmail.com',
        Password: null,
        VendorId: 0,
        AvailableVendors: [],
        GenderEnabled: false,
        Gender: null,
        FirstNameEnabled: false,
        FirstName: null,
        LastNameEnabled: false,
        LastName: null,
        FullName: 'PRO Cat DevCheck',
        DateOfBirthEnabled: false,
        DateOfBirth: null,
        CompanyEnabled: false,
        Company: 'nEW cOMPANY NAME pLAN NAME',
        CompanyLogo: 'https://dev.bildsy.com/Themes/Bildsy/Content/css/assets/images/company-placeholder.png',
        StreetAddressEnabled: false,
        StreetAddress: 'California 99, Los Molinos, California, 96055',
        StreetAddress2Enabled: false,
        StreetAddress2: null,
        ZipPostalCodeEnabled: false,
        ZipPostalCode: null,
        CityEnabled: false,
        City: 'Los Molinos',
        CountyEnabled: false,
        County: 'United States',
        CountryEnabled: false,
        CountryId: 237,
        AvailableCountries: [
          {
            Disabled: false,
            Group: null,
            Selected: false,
            Text: 'Select Country',
            Value: '0',
          },
          {
            Disabled: false,
            Group: null,
            Selected: false,
            Text: 'United States',
            Value: '237',
          },
        ],
        StateProvinceEnabled: false,
        StateProvinceId: 1678,
        AvailableStates: [
          {
            Disabled: false,
            Group: null,
            Selected: false,
            Text: 'Select State',
            Value: '0',
          },
        ],
        PhoneEnabled: false,
        Phone: null,
        FaxEnabled: false,
        Fax: null,
        LicenseNumber: null,
        AboutMe: null,
        LocalAddressId: 0,
        CustomerAttributes: [],
        RegisteredInStore: null,
        AdminComment: null,
        IsTaxExempt: false,
        Active: false,
        AffiliateId: 0,
        AffiliateName: null,
        TimeZoneId: null,
        AllowCustomersToSetTimeZone: false,
        AvailableTimeZones: [],
        VatNumber: null,
        VatNumberStatusNote: null,
        DisplayVatNumber: false,
        DisplayRegisteredInStore: false,
        StateName: 'California',
        CountryName: null,
        TwoLetterIsoCode: 'US',
        CreatedOn: '2022-02-17T14:10:56',
        LastActivityDate: '2022-07-08T18:32:07',
        LastIpAddress: null,
        LastVisitedPage: null,
        CustomerRoleNames: 'Registered, Professional',
        AvailableCustomerRoles: [],
        SelectedCustomerRoleIds: [],
        AvailableNewsletterSubscriptionStores: [],
        SelectedNewsletterSubscriptionStoreIds: [],
        ProjectTypeId: null,
        DisplayRewardPointsHistory: false,
        AddRewardPoints: {
          CustomerId: 0,
          Points: 0,
          Message: null,
          StoreId: 0,
          AvailableStores: [],
          ActivatePointsImmediately: false,
          ActivationDelay: 0,
          ActivationDelayPeriodId: 0,
          PointsValidity: null,
          CustomProperties: {},
        },
        CustomerRewardPointsSearchModel: {
          CustomerId: 0,
          Page: 1,
          PageSize: 10,
          AvailablePageSizes: null,
          Draw: null,
          Start: 0,
          Length: 10,
          CustomProperties: {},
        },
        AllowSendingOfPrivateMessage: false,
        AllowSendingOfWelcomeMessage: false,
        AllowReSendingOfActivationMessage: false,
        GdprEnabled: false,
        AvatarUrl: 'https://bildsydevstg.blob.core.windows.net/images/default-avatar_55.jpg',
        CustomerAddressSearchModel: {
          CustomerId: 0,
          Page: 1,
          PageSize: 10,
          AvailablePageSizes: null,
          Draw: null,
          Start: 0,
          Length: 10,
          CustomProperties: {},
        },
        CustomerOrderSearchModel: {
          CustomerId: 0,
          Page: 1,
          PageSize: 10,
          AvailablePageSizes: null,
          Draw: null,
          Start: 0,
          Length: 10,
          CustomProperties: {},
        },
        CustomerShoppingCartSearchModel: null,
        CustomerActivityLogSearchModel: null,
        CustomerBackInStockSubscriptionSearchModel: null,
        CustomerAssociatedExternalAuthRecordsSearchModel: null,
        WorkRadius: null,
        WorkRadiusUnit: null,
        IsBildsyAssured: false,
        Id: 23830,
        CustomProperties: {},
      },
    ],
    PagerModel: null,
    Editable: false,
    AvailableCities: null,
    Cities: null,
    IsImpersonate: false,
    ProjectImpersonateStatus: 0,
    IsSearch: false,
    ProjectInvitationTypeId: 0,
    ProfessionalId: 0,
    Data: null,
    Draw: null,
    RecordsFiltered: 0,
    RecordsTotal: 0,
    CustomProperties: {},
  },
  Success: true,
  Message: null,
};
