export const localStrings = {
  firstNameRequired: 'First name is required.',
  lastNameRequired: 'Last name is required.',
  emailIsRequired: 'Email is required.',
  invalidEmail: 'Invalid email address.',
  passwordIsRequired: 'Password is required.',
  addressIsRequired: 'Address is required.',
  required: 'Required',
  checkCharacter: 'Max 50 characters',
  acceptTermAndCondition: 'Please accept terms and conditions.',
  invalidPassword:
    'Your password must contain: \nAt least 8 characters \nAt least one uppercase \nAt least one lowercase \nAt least one digit',
  passwordsAreNotMatching: 'The password and confirmation password do not match.',
  newPasswordsAreNotMatching: 'The new password and confirmation password do not match.',
  newPasswordAreNotMatchingInSetPassword: 'The new password and confirm new password does not match.',
  selectCountry: 'Select Country',
  selectState: 'Select State',
  pleaseCheckYourEmail: 'Please check your email to complete the registration process.',
  register: 'Register',
  homeOwner: 'HomeOwner',
  resetPassword: 'Reset Password',
  enterEmail: 'Enter email address you use to sign in to.',
  weJustSentVerificationCode: 'We have just sent a verification code to the email address: ',
  enterCode: 'Enter Code',
  didNotReceiveACode: "Didn't receive a code? ",
  resend: 'Resend',
  running: 'Running',
  reStart: 'Restart',
  dashboard: 'Dashboard',
  signUpSuccessfully: 'Sign Up Successfully !',
  ok: 'Okay',
  advertise: 'Advertise',
  somethingWentWrong: 'Something went wrong.',
  googlePlayService: 'Google play service not available in you device.',
  alreadyInProgress: 'In progress',
  select: 'Select',
  selectAll: 'Select All',
  min: 'Min',
  max: 'Max',
  characters: 'Characters',
  youHaveInvited: 'You’ve invited these professional(s) to bid on your project.',
  recentBlogs: 'Recent Blogs',
  blogs: 'Blogs',
  errorWhileCamera: 'Something went to wrong, Please try after some time.',
  startProject: 'Start your first project!',
  projects: 'Projects',
  myProject: 'My Projects',
  completedProject: 'Completed Projects',
  archiveProject: 'Archived Projects',
  bidPending: 'Bid Pending',
  projectId: 'Project ID:',
  location: 'Location:',
  budget: 'Budget',
  dueDate: 'Expected Due Date',
  youCanAdd: 'You can add project site plan, maps, site images, etc.',
  camera: 'Camera',
  document: 'Document',
  cancel: 'Cancel',
  search: 'Search',
  expectedDateError: 'Expected completion date should be greater than Start date.',
  supportArea: "We're sorry, your area is not yet supported. Keep checking back for updates.",
  company: 'Company',
  firstProjectText: 'Start your first',
  projectNow: 'Project Now!',
  createNewProject: 'Create New Project',
  completed: 'Completed',
  projectAwarded: 'Project Awarded',
  inProgress: 'In Progress',
  draft: 'Draft',
  bidding: 'Bidding',
  unfulfilled: 'Unfulfilled',
  archived: 'Archived',
  companyName: 'Company Name',
  name: 'Name',
  type: 'Type',
  registered: 'Registered',
  professional: 'Professional',
  unitedStates: 'United States',
  noProject: 'No project available in the list.',
  noBlog: 'No blog available in the list.',
  noBlogOnSearch: 'No Blogs were found that matched your criteria.',
  expectedStartDate2: 'Expected Start Date',
  projectType: 'Project Type',
  info: 'Info',
  bids: 'Bids',
  chats: 'Chats',
  readMore: 'Read More',
  readLess: 'Read Less',
  markComplete: 'Mark Complete',
  markArchive: 'Mark Archive',
  call: 'Call',
  estimatedStartDate: 'Estimated Start Date',
  estimatedCompletion: 'Estimated Completion',
  amount: 'Amount',
  contact: 'Contact',
  placedOn: 'Placed on',
  descriptions: 'Description',
  complaints: 'Complaints',
  specialist: 'Specialist',
  reason: 'Reason*',
  project: 'Project',
  minDigit: 'Min 10 digits',
  maxDigit: 'Max 10 digits',
  numberOnly: 'Please enter numeric characters only.',
  questionModel: 'Are you sure you want to mark complete this project?',
  archiveModel: 'Are you sure you want to archive this project?',
  design: 'Design',
  legal: 'Legal',
  finance: 'Finance',
  mater: 'Mater',
  addNewComplaint: 'Add New Complaint',
  youHaveNoComplaint: 'You have no complaints at the moment !',
  complaint: 'Complaint',
  information: 'Information',
  raisedAgainst: 'Raised Against',
  raisedOn: 'Raised on',
  issueDescription: 'Issue Description',
  typeAMessage: 'Type a message',
  resolve: 'Resolve',
  complaintsId: 'Complaints ID',
  projectName: 'Project Name',
  status: 'Status',
  projectId2: 'Project ID',
  descriptionsIsRequired: 'Description is required',
  complaintEntity: 'ComplaintsCustomerConversation',
  conversation: 'Conversation',
  somethingWentToWrong: 'Something went to wrong with this file',
  bildsy: 'Bildsy',
  proposal: 'Proposal',
  bidPlaced: 'Bid Placed',
  bidDeclined: 'Bid Declined',
  viewProfile: 'View Profile',
  currentPasswordIsRequired: 'Current Password is required.',
  newPasswordIsRequired: 'New Password is required.',
  confirmPasswordIsRequired: 'Please enter confirm password.',
  confirmNewPasswordIsRequired: 'Confirm new password is required.',
  profile: 'Profile',
  by: 'By:',
  memberSince: 'Member Since',
  phone: 'Phone',
  aboutMe: 'About Me',
  localAddress: 'Address',
  yes: 'Yes',
  confirmation: 'Confirmation',
  confirmModal: 'Are you sure you want to Unawarded this project?',
  confirmModal2: 'Are you sure you want to reject this bid?',
  signOut: 'Sign Out',
  signOutConfirmation: 'Are you sure you want to Sign Out?',
  changePassword: 'Change Password',
  gallery: 'Gallery',
  confirmModal3: 'Are you sure you want to Award this project?',
  downloaded_message: 'File downloaded successfully',
  messageMustBeRequired: 'Message must be required',
  complaintMessageRequired: 'Complaint message must be required. Please write proper message',
  noNotification: 'No notification available!',
  archive: 'Archive',
  noBidsAvailable: 'No bids available at this time',
  thereIsNoProjects: 'There is no project attachment available.',
  messageSent: 'The message has been successfully sent to recipient',
  messageDelivered: 'The message has been successfully delivered to recipient',
  messageRead: 'The recipient has read your message',
  uploadingMessage: 'Please wait while uploading',
  downloadingIsInProgress: 'Downloading is in progress',
  requiredAboveZero: 'Required budget above 0.',
  complaintDetail: 'Complaint detail',
  postalCode: 'postal_code',
  country: 'country',
  State: 'administrative_area_level_1',
  locality: 'locality',
  town: 'sublocality_level_1',
  area: 'sublocality_level_2',
  nearestRoad: 'route',
  nameCity: 'name',
  streetNumber: 'street_number',
  blankDash: '--',
  downloadInProgress: 'Downloading is in progress',
  complaint2: 'complaint',
  chat: 'chat',
  maxBudgetError: 'Max: 500000',
  endDateShouldBeGreater: 'End date should be greater than or equal to Start date.',
  nothingSelected: 'Nothing selected',
  budgetInUSD: 'Budget (In USD)',
  clearAll: 'Clear All',
  startStr: 'start',
  notification: 'Notifications',
  endStr: 'end',
  Chat: 'Chat',
  onItemClick: 'onItemClick',
  ChatRoomNotAvailable: 'Chat room not available',
  allocated_five_minute_message: 'Allocated 5 minutes to unaward this project is now over.',
  add: 'Add',
  passwordMatching: 'Password must meet the following requirements:',
  checkLowerCase: 'At least one lowercase letter',
  checkUpperCase: 'At least one uppercase letter',
  checkNumber: 'At least one number',
  checkEightCharacter: 'At least eight characters',
  blogGuides:
    'DIY guides, expert insights about the construction industry, and how to get the most out of your Bildsy membership!',
  screenNotFound:
    "Whoops, that page is Gone.\nSorry, we can't find the page you're looking for. Please try going back to the previous page or reach out to us at support@bildsy.com to know more about the issue.",
  addComplaint: 'Add Complaint',
  filterToDateBeGreater: 'To Date should be greater than or equal to From Date.',
  attachmentUploadStatus: 'Project attachment uploaded successfully',
  helpButtonLink: 'http://167.172.209.57/help.html',
  imageAvif: 'image/avif',
  applicationOctetStream: 'application/octet-stream',
  imagePng: 'image/png',
  imageApng: 'image/apng',
  imageSvgXml: 'image/svg+xml',
  imageWebp: 'image/webp',
  imageBmp: 'image/bmp',
  imageGif: 'image/gif',
  imageJpeg: 'image/jpeg',
  imageJpg: 'image/jpg',
  imageJpe: 'image/jpe',
  imageJfif: 'image/jfif',
  Jpg: '.jpg',
  Jpeg: '.jpeg',
  Png: '.png',
  Webp: '.webp',
  Gif: '.gif',
  Jpe: '.jpe',
  Bmp: '.bmp',
  Jfif: '.jfif',
  Avif: '.avif',
  Apng: '.apng',
  PNG: '.PNG',
  JPG: '.JPG',
  WEBP: '.WEBP',
  GIF: '.GIF',
  BMP: '.BMP',
  JPE: '.JPE',
  JFIF: '.JFIF',
  JPEG: '.JPEG',
  youHaveNewMessages: 'You have received new message',
  logoutMessage: 'Are you sure you want to Sign Out?',
  blogList: 'blogList',
  subjectEmptyError: 'Enter the Subject',
  descriptionEmptyError: 'Enter the Description',
  homeowner: 'Homeowner',
  alert: 'Alert',
  OK: 'OK',
  help: 'Help',
  back: 'Back',
  projectCompletedMessage: 'Associated project was already completed by homeowner, so unable to access this complaint.',
  draftButton: 'draftButton',
  completeButton: 'completeButton',
  archiveButton: 'archiveButton',
  projectList: 'projectList',
  networkError: 'Network Error',
  deleteAccount: 'Delete Account',
  deleteConfirmation: "Are you sure you want to permanently delete your account? This can't be undone",
  deleteTitle: 'Delete Confirmation',
  enter: 'Enter',
  delete: 'DELETE',
  inBox: 'in below box',
  deleteError: 'Enter DELETE Keyword',
  reviews: 'Reviews',
  youHaveNoReview: 'You have no reviews at the moment!',
  addAReview: 'Add a Review',
  review: 'Review',
  reviewDescription:
    "If you're happy with the project, would you consider leaving a review? Your feedback can help future clients make informed decisions and ensure that we continue to deliver top-quality work.",
  later: 'Later',
  reportChat: 'Are you sure you want to report this comment to customer support?',
  reportComment: 'Report Comment',
  reported: 'Reported',
  alreadyRegistered: 'It seems you are already registered as a Professional. Please login',
  close: 'Close',
  reviewNow: 'Review Now',
};

export const tempStrings = {};
